--- lua 扫描器
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2024/12/26 14:31
LuaScan = {}

ldebug("loading LuaScan.lua")

require("GameDebug")

local this = {}
--- 一级函数缓存
local oneFunCache = {}
--- 二级函数缓存
local twoFunCache = {}

--- 检查是否存在一级函数
function LuaScan.checkHasTopFunc(name)
    local func = this.findTopFunc(name)
    if func == nil then
        this.print("没有找到一级函数：", name)
        return false
    end
    return true
end

---  检查是否存在二级函数
function LuaScan.checkHasTwoFunc(name)
    local funList = this.findTwoFunc(name)
    if funList == nil or #funList == 0 then
        this.print("没有找到二级函数：", name)
        return false
    end
    return true
end

--- 触发一级函数执行
function LuaScan.triggerTopFunc(name, ...)
    name = string.upper(name)
    local func = this.findTopFunc(name)
    if func == nil then
        this.print("没有找到一级函数：", name)
        return
    end
    this.print("触发一级函数：", func.methodName)
    local s, r = xpcall(func.fun, debug.traceback, ...)
    gameDebug.assertPrint(s, "调用一级函数异常：", func.methodName, "【", ..., "】\n", r)
    return r
end

--- 触发二级函数执行
function LuaScan.triggerTwoFunc(name, ...)
    name = string.upper(name)
    local funList = this.findTwoFunc(name)
    if funList == nil or #funList == 0 then
        this.print("没有找到二级函数：", name)
        return
    end
    for i, v in pairs(funList) do
        this.print("触发二级函数：", v.methodName)
        local s, r = xpcall(v.fun, debug.traceback, ...)
        gameDebug.assertPrint(s, "调用二级函数异常：", v.methodName, "【", ..., "】\n", r)
        if r ~= nil then
            return r
        end
    end
end

--- 查找 全局table 中的指定函 二级函数，是 全局table 虚拟类 下面注册的函数
--- @param name string 需要查找的函数名
function this.findTwoFunc(name)
    name = string.upper(name)
    local result = twoFunCache[name]
    if result == nil then
        result = {}
        local tables = this.GetTable()
        for fileName, fileTable in pairs(tables) do
            for methodName, v in pairs(fileTable) do
                if type(v) == "function" and string.upper(methodName) == name then
                    local infoMapping = {
                        ["fileName"]   = this.get_function_file(v),
                        ["methodName"] = fileName .. "." .. methodName,
                        ["line"]       = this.getFunctionLineNumber(v),
                        ["fun"]        = v,
                    }
                    this.print("找到二级函数：", infoMapping)
                    infoMapping["info"] = this.toString(infoMapping)
                    table.insert(result, infoMapping);
                end
            end
        end
        twoFunCache[name] = result
    end
    return result
end

--- 查找一级函数 就是全局函数
function this.findTopFunc(name)
    name = string.upper(name)
    local result = oneFunCache[name]
    if result == nil then
        for methodName, v in pairs(_G) do
            if type(v) == "function" and string.upper(methodName) == name then
                result = {
                    ["fileName"]   = this.get_function_file(v),
                    ["methodName"] = "_G." .. methodName,
                    ["line"]       = this.getFunctionLineNumber(v),
                    ["fun"]        = v,
                }
                this.print("找到一级函数：", result)
                oneFunCache[name] = result
                return result;
            end
        end
    end
    return result
end

function this.toString(funMapping)
    return funMapping.methodName .. "() 文件：" .. funMapping.fileName .. " line:" .. funMapping.line;
end

--- 获取当前虚拟机中所有的表
function this.GetTable()
    local result = {}
    for k, v in pairs(_G) do
        if type(v) == "table" then
            if k ~= "__index"
                    and k ~= "_G"
                    and k ~= "os"
                    and k ~= "io"
                    and k ~= "string"
                    and k ~= "utf8"
                    and k ~= "java"
                    and k ~= "math"
                    and k ~= "package"
                    and k ~= "debug"
                    and k ~= "coroutine"
            then
                result[k] = v
            end
        end
    end
    return result;
end

---获取函数所在的文件名
function this.get_function_file(func)
    local info = debug.getinfo(func)
    return info.short_src or "匿名文件"
end

---获取函数所在文件行号
function this.getFunctionLineNumber(func)
    local debugInfo = debug.getinfo(func)
    --获取不到函数名字，只能又文件名和行数表达了
    return debugInfo.linedefined or -1
end

local offPrint = true
function this.print(...)
    if offPrint then
        return
    end
    gameDebug.printLine(...)
end