--- == 比较器
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/27 10:43
---

require("ConditionService")

local ConditionComparator = {}
ConditionComparator.__index = ConditionComparator

ConditionService.registerComparator("==", function(self, target)
    return self == target
end)

ConditionService.registerComparator("!=", function(self, target)
    return self ~= target
end)

ConditionService.registerComparator(">", function(self, target)
    return self > target
end)

ConditionService.registerComparator(">=", function(self, target)
    return self >= target
end)

ConditionService.registerComparator("<", function(self, target)
    return self < target
end)

ConditionService.registerComparator("<=", function(self, target)
    return self <= target
end)