--- 条件
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/27 09:16
---

ConditionService = {}
ConditionService.__index = ConditionService

--- @class ConditionDTO 条件数据传输对象
--- @field actor Actor 角色
local ConditionDTO = {}

--- @class Condition 条件
--- @field processor ConditionProcessor 处理器名称
--- @field comparator function 比较器名称
--- @field values table<number, string> list类型值，
local Condition = {}

--- @class ConditionProcessor 条件服务
--- @field name string 条件名称
--- @field selfValueFunc function 获取当前值的函数
--- @field tipsFunc function 如果条件不满足，返回提示信息
local ConditionProcessor = {}

--- 条件处理器
--- @type table<string, ConditionProcessor>
local conditionProcessorMap = {}

--- @type table<string, function>
local conditionComparatorMap = {}

--- 注册条件
--- @param name string 条件名称
function ConditionService.registerProcessor(name, selfValueFunc, tipsFunc)
    name = string.upper(name)
    conditionProcessorMap[name] = setmetatable(
            {
                name          = name,
                tipsFunc      = tipsFunc,
                selfValueFunc = selfValueFunc
            },
            ConditionProcessor
    )
end

--- 注册比较器
--- @param name string 比较器名称
--- @param compare function 比较函数
function ConditionService.registerComparator(name, compare)
    name = string.upper(name)
    conditionComparatorMap[name] = compare
end

--- 获取条件处理器
--- @param name string 条件名称
--- @return ConditionProcessor 处理器
function ConditionService.getProcessor(name)
    name = string.upper(name)
    return conditionProcessorMap[name]
end

--- 获取比较器
--- @param name string 比较器名称
--- @return function 比较器
function ConditionService.getComparator(name)
    name = string.upper(name)
    return conditionComparatorMap[name]
end

--- 测试条件
--- @param conditionDTO ConditionDTO 条件数据传输对象
--- @param conditionCfg string 条件配置
--- @param errorCallBack function 错误回调
function ConditionService.testAll(conditionDTO, conditionCfg, errorCallBack)
    local conditionArrayString = string.split(conditionCfg, "&")
    --- @type table<number, Condition>
    local conditionList = {}
    for i, v in pairs(conditionArrayString) do
        local conditionArray = string.split(v, "#")
        local processor = ConditionService.getProcessor(conditionArray[1])
        if not processor then
            error("不存在条件处理器：" .. conditionArray[1])
        end
        local comparator = ConditionService.getComparator(conditionArray[2])
        if not comparator then
            error("不存在比较器：" .. conditionArray[2])
        end
        --- @type Condition
        local condition = {
            processor  = processor,
            comparator = comparator,
            values     = conditionArray
        }
        table.insert(conditionList, condition)
    end

    for i, v in pairs(conditionList) do
        local selfValue = tonumber(v.processor.selfValueFunc(conditionDTO, v))
        local targetValue = tonumber(v.values[3])
        if not v.comparator(selfValue, targetValue) then
            local tipsString = v.processor.tipsFunc(conditionDTO, v)
            if errorCallBack then
                errorCallBack(tipsString)
            else
                print(tipsString)
            end
            return false
        end
    end
    return true
end

function testcondition()
    --- @type Actor
    local conditionDTO = {
        actor = { lv = 1, job = 1 }
    }
    ConditionService.testAll(conditionDTO, "LEVEL#>=#10", function(tips)
        print(tips)
    end)

    ConditionService.testAll(conditionDTO, "job#==#2", function(tips)
        print(tips)
    end)
end