--- 等级条件处理器
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/27 10:40
---

require("ConditionService")

local ConditionProcessor = {}
ConditionProcessor.__index = ConditionProcessor

--- 提示
--- @param conditionDTO ConditionDTO 条件DTO
--- @param condition Condition 条件
--- @return void
function ConditionProcessor.tips(conditionDTO, condition)
    return "当前等级 " .. ConditionProcessor.selfValue(conditionDTO, condition) .. " 不符合 需求等级 " .. condition.values[3];
end

--- 自身值
--- @param conditionDTO ConditionDTO 条件DTO
--- @param condition Condition 条件
--- @return void
function ConditionProcessor.selfValue(conditionDTO, condition)
    return conditionDTO.actor.lv;
end

ConditionService.registerProcessor("Level", ConditionProcessor.selfValue, ConditionProcessor.tips)