--- 时间配置处理
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/12 09:18
---

DateService = {}
DateService.__index = DateService

--- @class DateProcessor 时间转换
--- @field convert function 时间转换函数
--- @field convertEndTime function 结束时间转换函数
local DateProcessor = {}

--- 时间类型转换
--- @type table<string, DateProcessor>
local typeActionMap = {}

--- @class DateExpression 时间表达式
--- @field startTime number 开始时间
--- @field endTime number 结束时间
--- @field valid function true 表示当前时间匹配，false 不在时间范围内
DateExpression = {}
DateExpression.__index = DateExpression

function DateExpression:new(startTime, endTime)
    local o = {}
    setmetatable(o, self)
    self.__index = self
    o.startTime = startTime
    o.endTime = endTime
    return o
end

function DateExpression:valid()
    local nowMillis = os.time() * 1000
    return self.startTime <= nowMillis and nowMillis <= self.endTime
end

function DateExpression:startTimeFormat()
    return DateService.formatyyyyMMddHHmmss(self.startTime)
end

function DateExpression:endTimeFormat()
    return DateService.formatyyyyMMddHHmmss(self.endTime)
end

function DateExpression:toString()
    return string.format("开始时间: %s 结束时间: %s", self:startTimeFormat(), self:endTimeFormat())
end

--- 转换时间配置
--- @param dto any 传递参数
--- @param cfgString string 时间配置字符串
--- @return DateExpression 时间
function DateService.convertBeginAndEnd(dto, cfgString)
    local paramArray = string.split(cfgString, "&")
    local p1 = paramArray[1]
    local p2 = paramArray[2]

    local paramsStart = string.split(p1, "#")
    --- @type DateProcessor
    local startProcessor = typeActionMap[string.upper(paramsStart[1])]
    if not startProcessor then
        error("类型异常: " .. paramsStart[1])
    end
    local startTime = startProcessor.convert(dto, paramsStart)
    local paramsEnd = string.split(p2, "#")

    --- @type DateProcessor
    local endProcessor = typeActionMap[string.upper(paramsEnd[1])]
    if not endProcessor then
        error("类型异常: " .. paramsEnd[1])
    end
    local endTime = endProcessor.convertEndTime(dto, startTime, paramsEnd)
    return DateExpression:new(startTime, endTime)
end

function DateService.convertString(dto, cfgString)
    local params = string.split(cfgString, "#")
    return DateService.convertParams(dto, params)
end

function DateService.convertParams(dto, params)
    local dateProcessor = typeActionMap[string.upper(params[1])]
    if not dateProcessor then
        error("类型异常: " .. params[1])
    end
    return dateProcessor.convert(dto, params)
end

--- 拷贝数组
--- @param array table 数组
--- @param startIndex number 开始索引
--- @param endIndex number 结束索引
function DateService.copySubArray(array, startIndex, endIndex)
    local result = {}
    for i = startIndex, endIndex do
        table.insert(result, array[i])
    end
    return result
end

--- 获取当前日期的午夜时间戳
--- @param currentTime number 当前时间戳, 单位毫秒
--- @return number 午夜时间戳, 单位毫秒
function DateService.dayMaxTimeByMillis(currentTime)
    currentTime = currentTime / 1000
    return DateService.dayMaxTime(currentTime)
end

--- 获取当前日期的午夜时间戳
--- @param currentTime number 当前时间戳, 单位秒
--- @return number 午夜时间戳, 单位毫秒
function DateService.dayMaxTime(currentTime)
    -- 获取当前日期的凌晨时间戳
    local currentDate = os.date("*t", currentTime)
    currentDate.hour = 23
    currentDate.min = 59
    currentDate.sec = 59
    return os.time(currentDate) * 1000
end

--- 获取当前日期的凌晨时间戳
--- @param currentTime number 当前时间戳, 单位毫秒
--- @return number 凌晨时间戳, 单位毫秒
function DateService.dayMinTimeByMillis(currentTime)
    currentTime = currentTime / 1000
    return DateService.dayMinTime(currentTime)
end

--- 获取当前日期的凌晨时间戳
--- @param currentTime number 当前时间戳, 单位秒
--- @return number 凌晨时间戳, 单位毫秒
function DateService.dayMinTime(currentTime)
    -- 获取当前日期的凌晨时间戳
    local currentDate = os.date("*t", currentTime)
    currentDate.hour = 0
    currentDate.min = 0
    currentDate.sec = 0
    return os.time(currentDate) * 1000
end

--- 注册时间类型
--- @param type string 时间类型
--- @param convert function 转换函数
--- @param convertEndTime function 结束时间转换函数
function DateService.register(type, convert, convertEndTime)
    local typeUpper = string.upper(type)
    if typeActionMap[typeUpper] then
        error("类型已存在: " .. typeUpper)
    end
    typeActionMap[typeUpper] = setmetatable(
            {
                convert        = convert,
                convertEndTime = convertEndTime
            },
            DateProcessor
    )
end

function DateService.formatyyyyMMddHHmmss(time)
    return DateService.format("%Y-%m-%d %H:%M:%S", time)
end

function DateService.format(format, time)
    -- 将毫秒时间戳转换为秒时间戳
    local seconds = math.floor(time / 1000)
    -- 使用 os.date 格式化为年月日时分秒
    local formattedTime = os.date(format, seconds)
    return formattedTime
end

function testdate(actor, cfg)
    ---@type DateExpression
    local dateExpression = DateService.convertBeginAndEnd(actor, cfg)
    print("testdate", cfg, dateExpression:valid(), dateExpression:toString())
end
