--- 时间配置处理
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/12 09:18
---

DateService = {}
DateService.__index = DateService

local typeActionMap = {}

--- 转换时间配置
--- @param cfgString string 时间配置字符串
function DateService.convertBeginAndEnd(extendParams, cfgString)
    local paramArray = string.split(cfgString, "&")
    local p1 = paramArray[1]
    local p2 = paramArray[2]

    local paramsStart = string.split(p1, "#")
    local actionStart = typeActionMap[string.upper(paramsStart[1])]
    if not actionStart then
        error("类型异常: " .. paramsStart[1])
    end
    local startTime = actionStart.convert(extendParams, paramsStart)
    local paramsEnd = string.split(p2, "#")
    local actionEnd = typeActionMap[string.upper(paramsEnd[1])]
    if not actionEnd then
        error("类型异常: " .. paramsEnd[1])
    end
    local endTime = actionEnd.convertEndTime(extendParams, startTime, paramsEnd)
    local nowMillis = os.time() * 1000
    local match = startTime <= nowMillis and nowMillis <= endTime
    return match, startTime, endTime
end

function DateService.convertString(extendParams, cfgString)
    local params = string.split(cfgString, "#")
    return DateService.convertParams(extendParams, params)
end

function DateService.convertParams(extendParams, params)
    local action = typeActionMap[string.upper(params[1])]
    if not action then
        error("类型异常: " .. params[1])
    end
    return action.convert(extendParams, params)
end

--- 拷贝数组
--- @param array table 数组
--- @param startIndex number 开始索引
--- @param endIndex number 结束索引
function DateService.copySubArray(array, startIndex, endIndex)
    local result = {}
    for i = startIndex, endIndex do
        table.insert(result, array[i])
    end
    return result
end

--- 获取当前日期的午夜时间戳
--- @param currentTime number 当前时间戳, 单位毫秒
--- @return number 午夜时间戳, 单位毫秒
function DateService.dayMaxTimeByMillis(currentTime)
    currentTime = currentTime / 1000
    return DateService.dayMaxTime(currentTime)
end

--- 获取当前日期的午夜时间戳
--- @param currentTime number 当前时间戳, 单位秒
--- @return number 午夜时间戳, 单位毫秒
function DateService.dayMaxTime(currentTime)
    -- 获取当前日期的凌晨时间戳
    local currentDate = os.date("*t", currentTime)
    currentDate.hour = 23
    currentDate.min = 59
    currentDate.sec = 59
    return os.time(currentDate) * 1000
end

--- 获取当前日期的凌晨时间戳
--- @param currentTime number 当前时间戳, 单位毫秒
--- @return number 凌晨时间戳, 单位毫秒
function DateService.dayMinTimeByMillis(currentTime)
    currentTime = currentTime / 1000
    return DateService.dayMinTime(currentTime)
end

--- 获取当前日期的凌晨时间戳
--- @param currentTime number 当前时间戳, 单位秒
--- @return number 凌晨时间戳, 单位毫秒
function DateService.dayMinTime(currentTime)
    -- 获取当前日期的凌晨时间戳
    local currentDate = os.date("*t", currentTime)
    currentDate.hour = 0
    currentDate.min = 0
    currentDate.sec = 0
    return os.time(currentDate) * 1000
end

--- 注册时间类型
--- @param type string 时间类型
--- @param convert function 转换函数
--- @param convertEndTime function 结束时间转换函数
function DateService.register(type, convert, convertEndTime)
    local typeUpper = string.upper(type)
    if typeActionMap[typeUpper] then
        error("类型已存在: " .. typeUpper)
    end
    local action = {};
    action.convert = convert;
    action.convertEndTime = convertEndTime;
    typeActionMap[typeUpper] = action
end

function DateService.formatyyyyMMddHHmmss(time)
    return DateService.format("%Y-%m-%d %H:%M:%S", time)
end

function DateService.format(format, time)
    -- 将毫秒时间戳转换为秒时间戳
    local seconds = math.floor(time / 1000)
    -- 使用 os.date 格式化为年月日时分秒
    local formattedTime = os.date(format, seconds)
    return formattedTime
end

function testdate(actor, cfg)
    local match, startTime, endTime = DateService.convertBeginAndEnd(actor, cfg)
    print("testdate", cfg, match, DateService.formatyyyyMMddHHmmss(startTime), DateService.formatyyyyMMddHHmmss(endTime))
end
