--- current.lua
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/12 10:02
---


require("DateService")


local this = {}

--- 转换时间
function this.convert(dto, params)
    local add = 0
    if #params > 2 then
        local newParams = DateService.copySubArray(params, 2, 3)
        add = DateService.convertParams(newParams)
    end
    -- 转换为时间戳
    return os.time() * 1000 + add
end

--- 计算结束时间戳
function this.convertEndTime(dto, startTime, params)
    return this.convert(dto, params)
end

DateService.register("current", this.convert, this.convertEndTime)