--- 今天时间凌晨
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/12 10:02
---

local this = {}

--- 转换时间为当天凌晨，并根据 addDay 增加或减少天数
function this.convert(extendParams, params)
    local addDay = tonumber(params[2]) or 0 -- 默认为 0 天

    -- 获取当前时间的时间戳
    local currentTime = os.time()
    currentTime = currentTime + (addDay * 24 * 60 * 60)
    -- 获取当前日期的凌晨时间戳
    local currentDate = os.date("*t", currentTime)
    currentDate.hour = 23
    currentDate.min = 59
    currentDate.sec = 59
    return os.time(currentDate) * 1000
end

--- 计算结束时间戳
function this.convertEndTime(extendParams, startTime, params)
    return this.convert(extendParams, params)
end

DateService.register("DayMax", this.convert, this.convertEndTime)