--- 小时
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/12 10:23
---


require("DateService")


local this = {}

--- 转换时间
function this.convert(dto, params)
    local minute = tonumber(params[2])
    -- 转换为时间戳
    return minute * 60 * 1000
end

--- 计算结束时间戳
function this.convertEndTime(dto, startTime, params)
    return startTime + this.convert(dto, params)
end

DateService.register("minute", this.convert, this.convertEndTime)