--- yyyymmdd.lua
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/12 10:02
---


require("DateService")


local this = {}

--- 转换时间
function this.convert(dto, params)
    local dateString = params[2]
    -- 提取年、月、日
    local year = tonumber(string.sub(dateString, 1, 4))
    local month = tonumber(string.sub(dateString, 5, 6))
    local day = tonumber(string.sub(dateString, 7, 8))

    -- 构造时间表
    local dateTable = {
        year = year,
        month = month,
        day = day,
        hour = 0,
        min = 0,
        sec = 0
    }
    -- 转换为时间戳
    return os.time(dateTable) * 1000
end

--- 计算结束时间戳
function this.convertEndTime(dto, startTime, params)
    local endTime = this.convert(dto, params)
    return endTime - 1;
end

DateService.register("yyyymmdd", this.convert, this.convertEndTime)