--- day
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/12 10:23
---

local this = {}

--- 转换时间
function this.convert(extendParams, params)
    local day = tonumber(params[2])
    -- 转换为时间戳
    return day * 24 * 60 * 60 * 1000
end

--- 计算结束时间戳
function this.convertEndTime(extendParams, startTime, params)
    return startTime + this.convert(extendParams, params)
end


DateService.register("day", this.convert, this.convertEndTime)