--- hhmmss.lua
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/12 10:02
---

local this = {}

--- 转换时间
function this.convert(extendParams, params)
    local dateString = params[2]
    -- 提取年、月、日
    local hour = tonumber(string.sub(dateString, 1, 2))
    local minute = tonumber(string.sub(dateString, 3, 4))
    local seconds = tonumber(string.sub(dateString, 5, 6))

    -- 获取今天的日期信息
    local today = os.date("*t")

    -- 设置指定的时间
    today.hour = hour
    today.min = minute
    today.sec = seconds

    -- 返回毫秒时间戳
    return os.time(today) * 1000
end

--- 计算结束时间戳
function this.convertEndTime(extendParams, startTime, params)
    return this.convert(extendParams, params)
end

DateService.register("hhmmss", this.convert, this.convertEndTime)