--- 小时
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2026/2/12 10:23
---

local this = {}

--- 转换时间
function this.convert(extendParams, params)
    local seconds = tonumber(params[2])
    -- 转换为时间戳
    return seconds * 1000
end

--- 计算结束时间戳
function this.convertEndTime(extendParams, startTime, params)
    return startTime + this.convert(extendParams, params)
end

DateService.register("seconds", this.convert, this.convertEndTime)