---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2025/6/10 10:36
---

Duplicate1002 = {}
Duplicate1002.__index = Duplicate1002

local this = Duplicate1002

local function getDuplicate()
    return 1002
end

local function checkDuplicate(map)
    return map.cfgId == getDuplicate()
end

function this.onMapCreate(map)
    if not checkDuplicate(map) then
        return
    end
    openHeart(map)
    dataPut(map, "$d1", "1", "地图数据")
    gameDebug.printLine("副本 " .. tostring(getDuplicate()) .. " 创建", map.uid, map.cfgId)
end

function this.onMapHeart(map)
    if not checkDuplicate(map) then
        return
    end
    local varData = dataGet(map, "$d1", "1")
    gameDebug.printLine("副本模块监听地图心跳", map, "地图数据", varData)
end

function this.onPlayerEnter(map, player)
    if not checkDuplicate(map) then
        return
    end
    gameDebug.printLine("玩家进入地图", map, player)
end

function this.onPlayerHeart(map, monster)
    if not checkDuplicate(map) then
        return
    end
    gameDebug.printLine("玩家心跳", map, monster)
end

function this.onMonsterCreate(map, monster)
    if not checkDuplicate(map) then
        return
    end
    gameDebug.printLine("怪物创建", map, monster)
end

function this.onMonsterEnter(map, monster)
    if not checkDuplicate(map) then
        return
    end
    gameDebug.printLine("怪物进入地图", map, monster)
end

function this.onMonsterHeart(map, monster)
    if not checkDuplicate(map) then
        return
    end
    gameDebug.printLine("怪物心跳", map, monster)
end

return this