---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2025/7/4 13:25
---

require("GameDebug")

function onStart()
    gameDebug.printLine("onStart")
end

function onStop()
    gameDebug.printLine("onStop")
end