--- 玩家相关
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2025/6/10 09:40
---

Player = {}

require("GameDebug")

function Player.onInit(player)
    gameDebug.printLine("玩家初始化", player)
end

function Player.onPlayerCreate(player)
    gameDebug.printLine("玩家创建", player)
end

return Player

