---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 無心道(15388152619).
--- DateTime: 2025/6/10 19:09
---

require("GameDebug")

function testList(list)
    gameDebug.printLine(list)
end

function onTick(...)
    gameDebug.printLine("onTick", ...)
end